language: node_js
node_js:
  - "0.10.26"
before_install:
  - npm install -g grunt-cli
  - git clone git://github.com/n1k0/casperjs.git ~/casperjs
  - cd ~/casperjs
  - export PATH=$PATH:`pwd`/bin
before_script:
  - casperjs --version
